- meta: flush_handlers
  tags: [service]

- name: Compose directory is present
  file:
    dest: "{{ compose_config_dir }}/{{ alias }}{{ container_name }}"
    state: directory
  tags: [service]

- name: Compose template is present
  template:
    src: "{{ container_name }}.yml.j2"
    dest: "{{ compose_config_dir }}/{{ alias }}{{ container_name }}/docker-compose.yml.ctmpl"
  register: result
  tags: [service]

- include: apply-service-template.yml

- name: DB container is pulled
  shell: docker-compose pull db
  args:
    chdir: "{{ compose_config_dir }}/{{ alias }}{{ container_name }}"
  environment:
    DOCKER_HOST: tcp://0.0.0.0:2375
  when: has_db is defined
  tags: [service]

- name: DB container is running
  shell: docker-compose up -d --no-recreate db
  args:
    chdir: "{{ compose_config_dir }}/{{ alias }}{{ container_name }}"
  environment:
    DOCKER_HOST: tcp://0.0.0.0:2375
  when: has_db is defined
  register: result
  tags: [service]

- include: apply-service-template.yml

- name: Container is pulled
  shell: docker-compose pull {{ container_name }}
  args:
    chdir: "{{ compose_config_dir }}/{{ alias }}{{ container_name }}"
  environment:
    DOCKER_HOST: tcp://0.0.0.0:2375
  tags: [service]

- name: Container is stopped
  shell: docker-compose stop {{ container_name }}
  args:
    chdir: "{{ compose_config_dir }}/{{ alias }}{{ container_name }}"
  environment:
    DOCKER_HOST: tcp://0.0.0.0:2375
  tags: [service]

- name: Container is removed
  shell: docker-compose rm -f {{ container_name }}
  args:
    chdir: "{{ compose_config_dir }}/{{ alias }}{{ container_name }}"
  environment:
    DOCKER_HOST: tcp://0.0.0.0:2375
  tags: [service]

- name: Container is up
  shell: docker-compose scale {{ container_name }}={{ service_instances }}
  args:
    chdir: "{{ compose_config_dir }}/{{ alias }}{{ container_name }}"
  environment:
    DOCKER_HOST: tcp://0.0.0.0:2375
  tags: [service]

- name: Simulate testing
  shell: sleep 15
  tags: [service]

- debug: var=services/{{ alias }}{{ container_name }}/color

- name: Color is updated
  consul_kv:
    key: services/{{ alias }}{{ container_name }}/color
    value: "{{ container_name }}"
    action: put
  tags: [service]

- name: nginx server template is present
  template:
    src: nginx-server.conf.j2
    dest: /data/nginx/servers/{{ nginx_conf_name }}.conf
  tags: [service]

- name: nginx Consul templates are present
  template:
    src: "{{ item.src }}"
    dest: "{{ item.ctmplDest }}"
  with_items: nginx_templates
  tags: [service]

- name: nginx Consul templates are applied
  shell: >
    consul-template \
      -consul localhost:8500 \
      -template "{{ item.ctmplDest }}:{{ item.dest }}:docker kill -s HUP nginx" \
      -once
  with_items: nginx_templates
  tags: [service]

- name: Consul configs are present
  template:
    src: consul_service.json.j2
    dest: /etc/consul.d/service-{{ alias }}{{ container_name }}.json
  register: health_result
  tags: [service]

- name: Consul is restarted
  shell: killall -HUP consul
  when: health_result|changed
  tags: [service]


