- name: Install preliminary packages
  apt: name={{item}} state=present force=yes 
  with_items:
    - apt-transport-https
    - python-setuptools
    - psmisc
  tags: [docker]

- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-jessie main
    update_cache: yes
    state: present
  when: ansible_distribution == 'Debian'
  tags: [docker]

- name: Ubuntu add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present
  when: ansible_distribution == 'Ubuntu'
  tags: [docker]

- name: Add GPG key for Docker repo
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  tags: [docker]

- name: Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: python-pip is present
  easy_install: name=pip state=latest
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker-py
    version: 1.6.0
    state: present
  tags: [docker]

- name: Local user is added to the docker group
  user:
    name: "{{ ansible_user_id }}"
    group: docker
  register: user_result
  tags: [docker]

- name: Configuration is present
  copy:
    src: docker.cfg
    dest: /etc/default/docker
  register: config_result
  when: ansible_distribution == "Ubuntu"
  tags: [docker]

- name: Systemd Configuration is present
  copy:
    src: docker.service
    dest: /lib/systemd/system/docker.service
  register: config_result
  notify:
    - reload systemctl
  when: ansible_distribution == "Debian"
  tags: [docker]

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  when: user_result|changed
  tags: [docker]
  
- name: IPv6 forwarding is activated
  shell: sysctl -w net.ipv6.conf.all.forwarding=1 net.ipv6.conf.{{ egress_if }}.accept_ra=2
  when: config_result|changed
  tags: [docker]
   
- name: Check docker-nat66 file presence
  stat: path=/usr/local/bin/docker-nat66
  register: dockernat66
  tags: [docker]

- name: Install docker-nat66
  get_url: 
    url: https://github.com/bstevant/docker-nat66/releases/download/0.1/nat66-docker
    dest: /usr/local/bin/docker-nat66
  when: dockernat66.stat.exists == false
  tags: [docker]

- name: Fix perms on /usr/local
  file: path={{item}} mode="u=rwx,g=rx,o=rx"
  with_items:
    - /usr/local/bin
    - /usr/local

- name: Apply executable permission
  file: path=/usr/local/bin/docker-nat66 mode="u+x,g+x"
  tags: [docker]

- name: Docker NAT66 systemd unit is present
  template:
    src: docker-nat66.service.j2
    dest: /lib/systemd/system/docker-nat66.service
    mode: 644
  notify:
    - reload systemctl
  when: ansible_distribution == "Debian"
  tags: [docker]

- name: Docker NAT66 is started
  service: name=docker-nat66.service state=started enabled=yes
  
- name: Add IPv6 address in /etc/hosts
  lineinfile: 
    dest: /etc/hosts
    line: "{{ ip }} {{ hostname }}"
