- hosts: iperf
  ignore_unreachable: True
  serial: 1
  roles:
    - iperf
  vars:
#    update_eiaas: True

- hosts: iperf
  ignore_unreachable: True
  serial: 10
  roles:
    - iperf-stop

- hosts: iperf2
  ignore_unreachable: True
  serial: 1
  roles:
    - iperf2
  vars:
#    update_eiaas: True
